apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: bslab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: express-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URL
              value: postgres://user:password@database-service:5432/mydb
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: bslab
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
