apiVersion: apps/v1
kind: Deployment
metadata:
  name: narrator-deployment
  namespace: bslab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: narrator
  template:
    metadata:
      labels:
        app: narrator
    spec:
      containers:
        - name: narrator
          image: narrator-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: narrator-service
  namespace: bslab
spec:
  selector:
    app: narrator
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
