apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  ports:
    - name: app
      port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: nuxt-frontend
