apiVersion: apps/v1
kind: Deployment
metadata:
  name: narrator-deployment
  namespace: bslab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: narrator
  template:
    metadata:
      labels:
        app: narrator
    spec:
      containers:
        - name: narrator
          image: narrator-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
