apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcriber-deployment
  namespace: bslab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transcriber
  template:
    metadata:
      labels:
        app: transcriber
    spec:
      containers:
        - name: transcriber
          image: transcriber-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
