apiVersion: v1
kind: Service
metadata:
  name: narrator-service
  namespace: bslab
spec:
  selector:
    app: narrator
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
