apiVersion: v1
kind: Service
metadata:
  name: transcriber-service
  namespace: bslab
spec:
  selector:
    app: transcriber
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
